### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by tehniemer** [muety/anchr-android#6]
I'm able to log into my insurance from the web, but every time I try to log in from the app I get an error `Failed to log in. Something went wrong`

**Comment by tehniemer** [comment]
OK, let me know when I can provide the logs you need.

**Comment by muety** [comment]
Alright, so do you mind if I close this issue?

**Comment by muety** [comment]
I'll give you a ping then 🙂

**Comment by muety** [comment]
I added basic logging capability and published a new version to the Play store. If you want, you can try with this new version and if the problem still occurs, post the error logs here. Use the three dots in the top right of the app to access them.

**Comment by muety** [comment]
@tehniemer Are you still having the issue?

**Comment by tehniemer** [comment]
Sorry, no, I eventually figured it out. It was an authentication issue on my end. I have 2FA on every exposed domain I host and that was blocking access. I use the API from some other services to bypass auth, but I don't see that an option in Anchr.
